debug: true
spring:
  datasource:
    url: jdbc:mariadb://localhost:12206/racetime
    username: racetime
    password: racetime
racetime:
  hashids:
    secret: 00aqmqedb05688z06d_%m%a==yu10am82ff)rcxk4il6@6%2=$
    min-length: 16
keycloak:
  auth-server-url: http://localhost:12000/auth
  realm: racetime
  resource: racetime-app
  public-client: true
